### PR TITLE
Add a method to construct a beta PERT distribution

### PR DESCRIPTION
**Pull request by jbowtie**
A beta PERT derives the shape parameters from the min, max, and mode -- this is often used in risk analysis, disease management, and other domains where an expert forecast or assessment is required.

This PR adds a static PERT method to the Beta class to instantiate a beta distribution from the min, max, and mode parameters. Note that I named the mode parameter "likely" to better match other libraries but would be happy to rename.

### CODE REVIEW

**Comment by cdrnet** [comment]
Great, thanks!

For API consistency it would be nice if it would optionally accept a random source. Could you add `System.Random randomSource=null` as optional last argument and just pass the value down to the constructor?

**Comment by cdrnet** [comment]
Thanks

**Comment by david-in-perth** [comment]
@jbowtie : Great idea. We could use that at my work, too.

It doesn't seem right as-is, though. The constructor accepts min, max, and mode, but returns a two-parameter Beta distribution, which has a range of [0,1]. So, for example, the distribution object returned by PERT(50, 65, 60) still has to be transformed to give values between 50 and 65.

A *four-parameter* Beta distribution, which has translation and scaling built-in, would be useful here.

Example references (from a quick Google search):

- https://www.me.utexas.edu/~jensen/ORMM/omie/computation/unit/project/beta.html
- http://math.stackexchange.com/questions/179537/four-parameter-beta-distribution-and-wikipedia
- http://www.itl.nist.gov/div898/handbook/eda/section3/eda366h.htm

**Comment by david-in-perth** [comment]
Also, lambda could be added as a fourth (optional) distribution parameter, with a default of 4.

**Comment by jbowtie** [comment]
I haven't seen cases where lambda is anything other than 4 but making it an optional parameter is a possibility in a future pull request.

Creating a four-parameter Beta distribution seems like a more ambitious undertaking suited to its own issue.

**Comment by david-in-perth** [comment]
> I haven't seen cases where lambda is anything other than 4 but making it an optional parameter is a possibility in a future pull request.

Yeah, I have no information to suggest that lambda values other than 4 are commonly used, so that's probably just a 'nice-to-have' / not important.

> Creating a four-parameter Beta distribution seems like a more ambitious undertaking suited to its own issue.

It might be less ambitious than you think, but I agree that it deserves its own issue, which I've created (#322). I also created an issue for the problem with the PERT method, as mentioned above (#321).

**Pull request merged**
