### PR TITLE
Fixed typo in TestBfgsMinimizer.FindMinimum_BigRosenbrock_Hard()

### PR DESCRIPTION
**Pull request by eriove**
Fixed typo in TestBfgsMinimizer.FindMinimum_BigRosenbrock_Hard() and added static property to avoid future similar typos

### CODE REVIEW

**Comment by eriove** [comment]
Just checked, the failing tests were failing [back in May 2015](https://github.com/mathnet/mathnet-numerics/commit/a506145eff7271401a0d23802e947f8af4b9e699) too.

**Comment by eriove** [comment]
@cdrnet Is there anything else you want me to fix on this before merging into unified_optimization or have you simply missed this PR?

I realized that my last comment was kind of cryptic, what I meant is that this fixes the failing tests related to optimization. The tests that are currently failing in the PR failed in the main branch too when the unified_optimizaton branch was created in May 2015.

**Comment by cdrnet** [comment]
Sorry for the delay and thanks for the clarification, and of course the fix! Merging now :)

**Comment by eriove** [comment]
Thanks. I believe I might have some more time to contribute to the optimization. Wrote some [questions](https://github.com/mathnet/mathnet-numerics/issues/283#issuecomment-211074947) in #283 too.

**Pull request merged**
