### PR TITLE
Fix infinite loop in RandomExtensions.NextBigIntegerSequence(0,1)

### PR DESCRIPTION
**Pull request by Silver-Fang**
I found a boundary condition that falls into an infinite loop. Fixed.

### CODE REVIEW

**Comment by Silver-Fang** [comment]
@cdrnet AppVeyor has some problem with .Net 6.0?

**Comment by cdrnet** [comment]
Yes, unfortunately the build system is in the middle of a migration, a state which was rather brittle and now apparently broken (although still works on my machine for some reason). I need to finish the migration to fix this properly. At least afterwards it will be technologically simpler, and rely more on the known dotnet cli tools.

**Comment by cdrnet** [comment]
That seems to have worked - master is green again :)

**Review by cdrnet — APPROVED** [review]
Thank you!

**Pull request merged**
