### PR TITLE
Minor improvement to "Getting started".

### PR DESCRIPTION
**Pull request by davidfgarcia**
Adding some .NET3.5/Win10 troubleshooting steps that I had to follow in order to get to a clean build, in case they help someone else.

### CODE REVIEW

**Comment by cdrnet** [comment]
Did you actually need .Net 3.5 builds? The normal .Net 4 build should not need anything related to 3.5 (if it does, we should fix it).

**Comment by davidfgarcia** [comment]
That was my experience, yes, I think the culprit was project “TestData”.

Once .NET 3.5 was installed and enabled on my machine (Win10, VS2015), I got a fully clean build.

**Comment by davidfgarcia** [comment]
Sure!

I’m very new to GitHub; I saw those two files in the changeset but they were not marked as “committed”, so I didn’t know what GH was going to do about them.

I’ll remove them and re-submit the pull request.

Thanks a lot!

**Comment by davidfgarcia** [comment]
Based on your other email, I guess the “Appendix” I added will have to be removed once the dependency on .NET 3.5 is removed? Does it make sense to add if for now, or should we make sure the solution builds without .NET 3.5 instead?

From: David Figueiras Garcia
Sent: Saturday, December 10, 2016 10:29 AM
To: 'mathnet/mathnet-numerics' <reply@reply.github.com>; mathnet/mathnet-numerics <mathnet-numerics@noreply.github.com>
Subject: RE: [mathnet/mathnet-numerics] Minor improvement to "Getting started". (#459)

Sure!

I’m very new to GitHub; I saw those two files in the changeset but they were not marked as “committed”, so I didn’t know what GH was going to do about them.

I’ll remove them and re-submit the pull request.

Thanks a lot!

**Comment by cdrnet** [comment]
Ah yes - this has indeed slipped in. We need TestData for all builds so I thought building it for .Net 3.5 should make it work without having to create 10 different project files for each target, but seems we cannot take that shortcut.

**Comment by cdrnet** [comment]
I think we should fix the solution to only require 3.5 if we actually want to build the 3.5 variant. The appendix info might still be useful for this, since there may be a need to build 3.5 on Windows 10 (e.g. when doing a full release), but maybe we could move it to [Build](http://numerics.mathdotnet.com/Build.html) instead of GettingStarted.

**Comment by davidfgarcia** [comment]
Replacing with new pull request.

**Comment by davidfgarcia** [comment]
Makes sense, I replaced the old PR with a new one (couldn’t figure out how to modify the existing one):

https://github.com/mathnet/mathnet-numerics/pull/460

Pull requests, commits and etc. will get a bit cleaner as I get more familiar with GitHub I hope. ☺

Thanks a lot, -david

**Comment by davidfgarcia** [comment]
Opened new issue to track the work suggested below:

https://github.com/mathnet/mathnet-numerics/issues/461

**Pull request closed without merging**
