### PR TITLE
RandomExtensions.NextBigIntegerSequence

### PR DESCRIPTION
**Pull request by Silver-Fang**
I'd like to add support for System.Numerics.BigInteger number type on random generation

### CODE REVIEW

**Comment by Silver-Fang** [comment]
I checked the current master code and found the code change wasn't actually applied. What happened? @cdrnet

**Comment by cdrnet** [comment]
Oh, weird - it looks like you reverted it again in #894 which was (accidentally?) opened from master instead of from a feature branch?

**Comment by cdrnet** [comment]
I can revert the revert :)

**Comment by Silver-Fang** [comment]
> I can revert the revert :)

Yes. I accidentally commit the function extension to the bug fix branch so I reverted it. Now this is the side effect. Revert the revert it please. 😀

**Comment by cdrnet** [comment]
Should be back: e7bcab1

**Pull request merged**
