### PR TITLE
465 sparse compressed row matrix storage

### PR DESCRIPTION
**Pull request by arthurvb**
See issue #465

Also found bug in clearing data for sparse vectors. 
Used the following test code but did not yet find an appropriate class to put this test-code in so you may add it if necessary:

```
        /// <summary>
        /// Test whether Rows can be extracted correctly in all their forms
        /// </summary>
        [Test]
        public void CanExtractRows()
        {
            const int Order = 10;
            var matrix = Matrix<double>.Build.Sparse(Order, Order);
            // create rows
            for (int i = 0; i < Order; ++i)
            {
                for (int j = 0; j < Order; ++j)
                {
                    if ((j== 0) || ((i % j) == 0))
                    {
                        matrix[i, j] = (double) i;
                    }
                }
            }
            // just some rows
            for (int i = 0; i < Order; ++i)
            {
                foreach(var item in matrix.Row(i).EnumerateIndexed())
                {
                    if ((item.Item1 == 0) || ((i % item.Item1) == 0))
                    {
                        Assert.AreEqual(item.Item2, (double) i);
                    }
                    else
                    {
                        Assert.AreEqual(item.Item2,  0.0);
                    }
                }
            }
            //CopySubRowTo
            for (int i = 0; i < Order; ++i)
            {
                Vector<double> sparseVector = Vector<double>.Build.Sparse(Order);
                for (int j = 0; j < Order; ++j)
                {
                    if ((j % 2) == 0)
                    {
                        sparseVector[j] = -1.0;
                    }
                }
                matrix.Storage.CopySubRowTo(sparseVector.Storage, i, i, Math.Min(Order, i + 1),
                    Math.Min(3, (Order - (i+1))));
                foreach (var item in sparseVector.EnumerateIndexed())
                {
                    if ((item.Item1 >= i +1) && (item.Item1 <  ((i + 1) + 3)) && (item.Item1 < (Order - 1)))
                    {
                        Assert.AreEqual(item.Item2, matrix[i,item.Item1 + 1]);
                    }
                    else
                    {
                        if ((item.Item1 % 2) == 0)
                        {
                            Assert.AreEqual(item.Item2, -1.0);
                        }
                        else
                        {
                            Assert.AreEqual(item.Item2, 0.0);
                        }
                    }
                }
            
            }
```

### CODE REVIEW

**Comment by arthurvb** [comment]
Sorry, I see that there are still some issues, looking into it..

**Comment by arthurvb** [comment]
For completeness, new testcode:
```
        /// <summary>
        /// Test whether Rows can be extracted correctly in all their forms
        /// </summary>
        [Test]
        public void CanExtractRows()
        {
            const int Order = 100;
            var matrix = Matrix<double>.Build.Sparse(Order, Order);
            // create rows
            for (int i = 0; i < Order; ++i)
            {
                for (int j = 0; j < Order; ++j)
                {
                    if ((j== 0) || ((i % j) == 0))
                    {
                        matrix[i, j] = (double) i;
                    }
                }
            }
            // just some rows
            for (int i = 0; i < Order; ++i)
            {
                foreach(var item in matrix.Row(i).EnumerateIndexed())
                {
                    if ((item.Item1 == 0) || ((i % item.Item1) == 0))
                    {
                        Assert.AreEqual(item.Item2, (double) i);
                    }
                    else
                    {
                        Assert.AreEqual(item.Item2,  0.0);
                    }
                }
            }
            //CopySubRowTo
            for (int i = 0; i < Order; ++i)
            {
                Vector<double> sparseVector = Vector<double>.Build.Sparse(Order);
                for (int j = 0; j < Order; ++j)
                {
                    if ((j % 2) == 0)
                    {
                        sparseVector[j] = -1.0;
                    }
                }
                matrix.Storage.CopySubRowTo(sparseVector.Storage, i, i, Math.Min(Order, i + 1),
                    Math.Min(3, (Order - (i+1))));
                foreach (var item in sparseVector.EnumerateIndexed())
                {
                    if ((item.Item1 >= i +1) && (item.Item1 <  ((i + 1) + 3)) && (item.Item1 < Order))
                    {
                        Assert.AreEqual(item.Item2, matrix[i, item.Item1 - 1]);
                    }
                    else
                    {
                        if ((item.Item1 % 2) == 0)
                        {
                            Assert.AreEqual(item.Item2, -1.0);
                        }
                        else
                        {
                            Assert.AreEqual(item.Item2, 0.0);
                        }
                    }
                }
            }
        }
```

**Comment by cdrnet** [comment]
Thanks for working on this! I'm looking forward to pull this in, but I'll need some time to review the changes as this is certainly one of the more complicated and thus error-prone areas of the code base.

**Comment by arthurvb** [comment]
100% agreed, still finding some (little) corner cases myself

**Comment by cdrnet** [comment]
Merged, thanks again!

**Pull request merged**
