### PR TITLE
Add debugger display proxy to vector and matrix

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Looks like this:
devenv_qM9lB3QDQE
devenv_W7cS6nEDfU

Previous display for vector to compare:
devenv_jUOC7ugMjE

### CODE REVIEW

**Comment by jkalias** [comment]
Cool!

**Comment by DoctorKrolic** [comment]
CI is green, merge?

**Comment by jkalias** [comment]
It’s fine for me, unfortunately I don’t have merge rights for this repo. I tried to contact @cdrnet for some stuff I needed for the Spatial repo, but no luck either 😔

**Comment by DoctorKrolic** [comment]
I'm worried that @cdrnet's last activity was over a month ago. If he is the only person with full rights for this repo and is not responding it might not end well...

**Comment by jkalias** [comment]
This is also my concern :(

**Comment by DoctorKrolic** [comment]
Any updates here?

**Comment by jkalias** [comment]
Not from my side. I have started to be worried about @cdrnet ’s health. He doesn’t respond to any messages

**Comment by cdrnet** [comment]
Very useful, thank you!

**Pull request merged**
