### PR TITLE
Updated some (hyperbolic) trig functions

### PR DESCRIPTION
**Pull request by diluculo**
PR for #539

### CODE REVIEW

**Comment by diluculo** [comment]
I missed a case of infinite `denom`. I will be back. Sorry.

**Comment by diluculo** [comment]
Done.

To avoid overflow, if `x > asinh(max)/4 = 177.62`, the approximation of `sinh^2(x) ~= exp(-2|x|)/4` is applied. This limit value was from Kahan's paper. Please see the updated pdf file in #539.

For reference, in the first commit, `x > asinh(sqrt(max))/4 = 355.58` was used and I found a overflow of `denom` in 354 < x < 355.58.

**Comment by diluculo** [comment]
The approximation of `sinh^2(x)` is used if `x >= 22.0`. This value is taken from freeBSD.

**Comment by cdrnet** [comment]
Great, thanks a lot once more!

**Pull request merged**
