### PR TITLE
Cleaning up native memory usage and other minor issues

### PR DESCRIPTION
**Pull request by cuda**
This addresses issues #325, #326 and #327.

### CODE REVIEW

**Comment by cdrnet** [comment]
Great, thanks again Marcus! Sorry for the delay, just back from vacation...

Quick question: was the change to drop the wildcard file inclusion approach in UnitTests-MKL.csproj intentional?

**Comment by cuda** [comment]
> was the change to drop the wildcard file inclusion approach in UnitTests-MKL.csproj intentional?

No, that was a mistake. Can easily revert it?

**Comment by cdrnet** [comment]
Ok. Yes, I can revert just that file easily after pulling.

**Comment by cuda** [comment]
OK, thanks.

**Pull request merged**
