### PR TITLE
Improve convergence for symmetrical functions for Nelder Mead Simplex

### PR DESCRIPTION
**Pull request by eriove**
As discussing in #632 this is a pull request to solve #501 in the way suggested by @EricScottSalem.

Test taken from #501 by @MMAvanEnkhuizen

### CODE REVIEW

**Comment by EricScottSalem** [comment]
@eriove Any idea whats wrong with the build here?

**Comment by eriove** [comment]
Not sure, seems very unlikely that it is related to changes in this request.

**Comment by EricScottSalem** [comment]
It looks like in both cases the build server was unable to use the required .NET Core version.  Perhaps just rerunning the build will solve this?  I dont see how to do that, though.
@cdrnet  ?

**Comment by cdrnet** [comment]
Yes, the failing builds are unrelated - neither TravisCI nor Azure Pipelines seem to support .Net Core 2.2.4 (SDK 2.2.106) yet. AppVeyor is what counts for now. Sorry for the confusion.

**Comment by EricScottSalem** [comment]
Are we waiting for the build servers to catch up to approve this PR or can we do so without Travis and Azure?

**Comment by cdrnet** [comment]
Looks good to me as well. Thanks again!

**Pull request merged**
