### PR TITLE
Added code to calculated Standard Error of the Regression for a linear…

### PR DESCRIPTION
**Pull request by ardave**
… model.

Feedback welcome.  If this is suitable, I can continue on with the rest of the parts of Issue #412 .   

If not, please give feedback and I can rework.

### CODE REVIEW

**Comment by cdrnet** [comment]
Thanks for putting this together, including the test!

I do wonder about the right choice for the denominator. In `Statistics` we typically have two variants, one for cases where the provided data is the full population (e.g. `Statistics.PopulationVariance`) and one for cases where the data is a sample only (e.g. `Statistics.Variance`). The former typically has `N` as denominator, the latter `N-1`. There is a similar note in the linked page, arguing that in the sampling case, the denominator shall be `N-k` where `k` is the order (degree of freedom) of the regression. I wonder whether we should provide two variants as well, or have an additional `degreesOfFreedom` or `order` argument to control the normalization?

**Comment by ardave** [comment]
I can certainly do that, and submit the changes in a new PR.

**Comment by ardave** [comment]
See if I interpreted the requirements correctly with this second commit.

I can continue trying to rebase/squash the commits into 1 if it's important - git is acting up on my machine and feeding gibberish into my rebase-todo file right now.

Also, I can change the method signatures to require arrays rather than ienumerables; doing so would allow me to guard more proactively against the `degreesOfFreedom > numberOfSamples` case, at the top of the method, by relying on the array.length properties rather than materializing the sequences.  For now, I've just tried to mimic the style of the existing code that is closest to the new code that I have added.

**Comment by cdrnet** [comment]
Merged - thanks again!

**Comment by ardave** [comment]
Cool.  I'll continue on now with the more parts of this Issue.

**Pull request merged**
