### PR TITLE
Added PCHIP

### PR DESCRIPTION
**Pull request by febkor**
Added PCHIP (piecewise cubic Hermite interpolating polynomial).
This is a somewhat popular request on the [feedback forum](http://feedback.mathdotnet.com/forums/2060-math-net-numerics/suggestions/15436-implement-matlab-s-pchip-interpolation-algorithm).
The algorithm is based on that in "Numerical Computing with MATLAB" (Clive Moler).

I'm not so sure about the name, however.
Matlab/Octave and SciPy call this pchip, NAG calls this monotonic_interpolant while the original paper by Fritsch and Carlson (1980) is titled "Monotone Piecewise Cubic Interpolation".

### CODE REVIEW

**Comment by febkor** [comment]
Not sure why the Travis CI build is failing. Relates to F# which I have not touched in my PR.

**Comment by cdrnet** [comment]
Looks good to me, thanks a lot!

Yes, the Travis error is unrelated.

**Comment by cdrnet** [comment]
> I'm not so sure about the name, however.

The chosen name `InterpolatePchip` looks good to me. We have more descriptive names in the `Interpolate` shortcut class in the root namespace, where we could maybe add `CubicSplineMonotone`.

**Comment by febkor** [comment]
Thanks! Should I add `CubicSplineMonotone` to `Interpolate.cs`? Happy to do it.

**Comment by cdrnet** [comment]
Yes, that would be great. Thanks!

**Comment by febkor** [comment]
Thanks, done.

**Comment by cdrnet** [comment]
Perfect, thanks a lot!

**Pull request merged**
