### PR TITLE
Unified optimization

### PR DESCRIPTION
**Pull request by eriove**
As I understand [this list](https://github.com/mathnet/mathnet-numerics/issues/283#issuecomment-136821287) in #283 there are no blocking issues to merge this into the main branch.

I did a rebase of the unified_optimization branch and fixed the merge problems. All tests pass. By merging this it will be easier to make new contributions for those who are interested in optimization and it will be usable for those that use the NuGet packages.

### CODE REVIEW

**Comment by eriove** [comment]
Changed language version to 6, I had just changed it for ReSharper and not in the project settings

**Comment by eriove** [comment]
It seems fairly simple to fix the warnings, I'll do that tonight

**Comment by cdrnet** [comment]
Thanks a lot! I'm looking forward to finally merge this into mainline.

**Comment by eriove** [comment]
Fixed the warnings introduced by the new code

**Comment by cdrnet** [comment]
Finally in master. Thanks a lot, again!

**Pull request merged**
